# Generated by Django 4.2.5 on 2023-10-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
